### ISSUE TITLE
[FEATURE] Specifying exact value from ClickGui

### ISSUE THREAD

**Issue by TASelwyn** [John200410/rusherhack-issues#1185]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

 I suggest being able to double click a value in click gui, such as RotationLock's "Custom Yaw Value" and being able to type in a value instead of using a value slider.

**Is your feature request related to a problem? Please describe.**

Using sliders, can sometimes pick values you don't want, for example jump from 42 to 51 or from 4.8 to 5.1 when you want 4.95.  This can be frustrating to get a precise value, forcing people to use the module text commands to be able to percisely pick a value.

**Comment by SoggyBacco** [comment]
u can do this with commands

**Comment by TASelwyn** [comment]
> forcing people to use the module text commands to be able to percisely pick a value.

I referenced this saying "module text commands". 
It was just a suggestion to make it easier than finding the exact module setting string to use for the command.

**Comment by iTwisten** [comment]
yes

**Comment by HausemasterIssue** [comment]
This in my opinion can be a tad bit tedious and is not very fast or efficient to change a value, plus i bet it would take a decent amount of work to implement. an option for this in the clickgui could be good but i personally like the traditional slider more. if this were to get implemented it should not be forced and just as an option due to this being better or not subjective

**Comment by browsky300** [comment]
this has been added (using middle click) and will be in the next update
