### ISSUE TITLE
[FEATURE] ElytraFly improvement

### ISSUE THREAD

**Issue by Eskerepvp** [John200410/rusherhack-issues#1203]
Code the new 2b2t elytra fly bypass

**Comment by HausemasterIssue** [comment]
Yes

**Comment by master7720** [comment]
> Code the new 2b2t elytra fly bypass

skid inpacts elytra fly it bypasses

**Comment by Justgamer101** [comment]
> skid inpacts elytra fly it bypasses

how to skid in a pact to elytra fly bypass?

**Comment by TwoThreeTwo** [comment]
Donate me 25 dollars and i'll teach you how to deobfuscate rusherhack !!!!!

**Comment by Justgamer101** [comment]
why would anyone do that.

**Comment by TwoThreeTwo** [comment]
Because I shall teach you the ways of deobfuscating rusherhack and making john mad!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Justgamer101** [comment]
ok

**Comment by Ozynt** [comment]
Its coming in the next update :)

**Comment by Ozynt** [comment]
added now
