### ISSUE TITLE
[FEATURE]MCXP

### ISSUE THREAD

**Issue by NotJohnmcswag** [John200410/rusherhack-issues#1211]
**What feature would you like to be added.**
when you middle click it silently throws xp

**Is your feature request related to a problem? Please describe.**
no

**Additional context**

**Comment by HausemasterIssue** [comment]
TBH the whole AutoEXP module could use a rewrite or an update.

**Comment by John200410** [comment]
Instead of limiting this to MiddleClick I thought it would be a better idea to add it to the EXPFast module, so people could have other choices for the keybind (as well as have pitch setting)

![image](https://user-images.githubusercontent.com/43681932/155901409-d63fa450-65b0-4299-843d-259a46866ac4.png)

Added in the next update.

**Comment by NotJohnmcswag** [comment]
thats good but can you make it an option to hold it instead of making it a toggle, unless its already like that
