### ISSUE TITLE
[BUG] Illegal Bedrock not rendering in view of render distance

### ISSUE THREAD

**Issue by birsk-was-taken** [John200410/rusherhack-issues#1337]
When illegal bedrock enters my render distance, and I have the illegal bedrock option turned on, it doesn't draw a tracer or draw a box around it.

Go to any illegal bedrock on any server or world and have illegal bedrock on the search module on, and it will not draw a tracer.

I am using optifine and baritone as my other mods.

I expect for it to draw a tracer to the illegal bedrock, but it does not.

![2022-08-05_10 14 58](https://user-images.githubusercontent.com/81936635/183095907-e43c0ff3-b0a4-453f-bc46-96540eb59cb8.png)

**Comment by Luigit12** [comment]
Issue #1337 nice

**Comment by TwoThreeTwo** [comment]
Include a title next time.

**Comment by TwoThreeTwo** [comment]
Hi birsk-was-taken,

This seems to be an issue on your end...

What I'm talking about is that do not have the blocks mode on in Search, this is vital because it highlights any **blocks**, just like Bedrock. It's okay, all make mistakes 😄 

Here's the video of me showing your issue and a correct way to work around it. 
Hope this helps :D
https://user-images.githubusercontent.com/83801755/185703851-8055ce1b-e250-4364-a7e0-b2a14f864a5a.mp4
