### ISSUE TITLE
[FEATURE] Lists rendering way choice, like for what side and what height.

### ISSUE THREAD

**Issue by VoidBite1** [John200410/rusherhack-issues#1370]
**What feature would you like to be added.**
Like that you can choose for it to go topdown or bottomup, or that the modules stick to the left or right side, able to be selected for every individual module, it'd also be nice to have this option for the tabgui.

**Is your feature request related to a problem? Please describe.**
Yea, I'm trying to put multiple hud things under each other, and now my lists are rendering the wrong way around.

**Additional context**
nope

**Comment by TwoThreeTwo** [comment]
This can be solvable by using HUD -> Clamping, allowing it to be moved from top to left to right to down can be done automatically as it acts like it is cut into 4 sqaures that act as invisible grids and whenever you go past one of them it triggers them and causes them to switch into the positon of where that side is originally going to be. I'm going to close this issue because I think that is what you mean. Reopen it if you think I am not talking about what you want.
