### ISSUE TITLE
[FEATURE] PLUS ONLY dqs 

### ISSUE THREAD

**Issue by CaptainTheBeam** [John200410/rusherhack-issues#323]
**What feature would you like to be added.**
A detailed explanation of what this feature should be.

Something like dqs that would dm u on discord if u were attacked or a player entered ur visual range or someone msged u. also with baritone to allow u to travel while afk that then dms u on discord when ur destination has been reached. 

Like this https://youtu.be/wNT4ayGMmz4 

**Is your feature request related to a problem? Please describe.**

no

**Additional context**

**Comment by tycrek** [comment]
The DQS source code is a under a private proprietary license. In other words: John won't be able to add it unless Dewy makes a licensing agreement (which is unlikely).

Also, DQS requires a separate server in order to run your account. There's no valid reason to integrate a queue proxy into RusherHack (or any client for that matter). If your computer is going to be on with the client open anyways, just connect to the server directly.

**Comment by CaptainTheBeam** [comment]
i know but he can make something like it

**Comment by FarmerJoe2b2t** [comment]
dqs is a cringe paste, and it would be much easier to just have the client use rusherboi to message you than to make a queue proxy

**Comment by John200410** [comment]
I have no plans of adding this.

**Comment by CaptainTheBeam** [comment]
make a plan of adding this
