### ISSUE TITLE
AutoTrap

### ISSUE THREAD

**Issue by 420lechxis** [John200410/rusherhack-issues#707]
My autotrap don't work on players, it only works on fake players

**Comment by jumboman32** [comment]
Can you please provide more information or a video?

**Comment by ProfKambing** [comment]
No

**Comment by John200410** [comment]
What are your settings?

**Comment by 420lechxis** [comment]
https://ibb.co/7WBDHbm

**Comment by John200410** [comment]
Can you record the problem?

**Comment by jumboman32** [comment]
@420lechxis

**Comment by 420lechxis** [comment]
https://www.mediafire.com/file/tboxf42usfacrfx/autotrap.mp4/file

**Comment by HarryPotter42MC** [comment]
Sadly, I cant help in this conversation in the form of a video file because I cannot record stuff without big fps and lag spike problems but I can show it in a screenshare. Try autotrap with this config on flat ground, in the middle of blocks and when the target is between blocks. It doesnt place the supporting blocks it needs to trap soemone fully

![grafik](https://user-images.githubusercontent.com/82435253/117318754-02776b80-ae8b-11eb-8f9e-5e43e5342e80.png)

**Comment by jumboman32** [comment]
> Sadly, I cant help in this conversation in the form of a video file because I cannot record stuff without big fps and lag spike problems but I can show it in a screenshare. Try autotrap with this config on flat ground, in the middle of blocks and when the target is between blocks. It doesnt place the supporting blocks it needs to trap soemone fully
> 
> 
> 
> ![grafik](https://user-images.githubusercontent.com/82435253/117318754-02776b80-ae8b-11eb-8f9e-5e43e5342e80.png)
> 
> 
That is the point of that mode.
